services:
  streamx:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./data:/data
    environment:
      - ORIGIN=${ORIGIN:-http://localhost:3000}
      - TMDB_API_KEY=${TMDB_API_KEY:-}
    restart: unless-stopped
